### ISSUE TITLE
tldraw licensing change

### ISSUE THREAD

**Issue by rzmk** [AlbertBrand/slidev-addon-tldraw#2]
I think the tldraw licensing details may have changed recently from the link provided in this repo's README.

https://github.com/AlbertBrand/slidev-addon-tldraw/blob/ba351d8802ddcd41cd01d578715043e7046f137f/README.md?plain=1#L72

**Comment by AlbertBrand** [comment]
Agreed, it has changed since tldraw 3.0. Still a custom license though.

**Comment by rzmk** [comment]
There seems to be commercial usage available now too with certain conditions but this README says only free for non-commercial use. Since it's a custom license that can be updated anytime, maybe just the mention of the custom license in the README works instead of the last part of the sentence mentioning it's "only free for non-commercial use" to avoid having to keep the availability updated in the README (so the user can check themselves)?

**Comment by AlbertBrand** [comment]
Changed the README for 0.3.0 and it now only points to the license.
